# Generated by Django 4.2 on 2023-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cod_prod',
            new_name='unidad_prod',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='desc_prod',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca_prod',
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_min_prod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_prod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_prod',
            field=models.CharField(choices=[('O', 'OK'), ('W', 'Warning'), ('D', 'Danger')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
