# Generated by Django 4.2 on 2023-06-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cod_prod_producto_unidad_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_prod',
            field=models.CharField(editable=False),
        ),
    ]
