# Generated by Django 4.2 on 2023-06-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producto_estado_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cant_min_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cant_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_prod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
