# Generated by Django 4.2 on 2023-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_valor_total_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor_total_prod',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
