# Generated by Django 4.2 on 2023-06-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_producto_valor_total_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cant_ing_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_sal_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cant_prod',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6),
        ),
    ]
