# Generated by Django 4.2 on 2023-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producto_cant_ing_prod_producto_cant_sal_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cant_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
