# Generated by Django 4.2 on 2023-06-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_producto_cant_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_valor_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_valor_salida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'tablero',
                'verbose_name_plural': 'tableros',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_total_ing_prod',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_total_sal_prod',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
