# Generated by Django 4.2 on 2023-06-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dashboard_producto_valor_total_ing_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='total_cantidad_ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_cantidad_salida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
